language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ls2MQFHwyOW5wmgPppNdNcMEnXncrlHFcSMLabE8RGUw3bOKuIFYYdEaUoXSeAoEe4XcGhMI9WoRxWsSzzCcqN0m747+WXTAA0Y+TuhaOth6kIxkD7s2RU6+6KGITB4udBrjZkrKxciLl3qFRquqXfMO13o+thlZ7k+PjcSpZlIaWWKl2Dqd5ym0MtdTuIJcP2zDLC1HdR51vAS8Na5Iz3bFRH9JdP3gCiw4d3+NVR7GWBKh8+5XTKdd5wk8Owr+reYZYniNjADj8kpzk0C+PEFHy6s0uOEqJYb1QMhdFYaSfRIdrAP/JylI4c1xh+b/bTjdFTiJycAeSeUkekexggio0UVkcAHOswnq1TG7GqBtnSwkTF43yBjd3uROLittGKeDc5mwfUyFTNm+HbrxEYbcVhCLNEDj3/pb660+h703Hwlw4AZbxN20a1kZ63VyVGyjyf/nGmM81M4PNv3fZw6OMWTvu6lwML0l0RCYr0Em9XcNSxDyCh7ebH6doEHFcWIyuy9fhMpt8zrbFkJJhUq4FyY/x3FtjOSsIdNEeIinbktXeWVMrGr4JeBD743grv0lbKrp0knpQjVwiKtcpYavc47OfjfAlQ1x4UdxbdeqmGAUSAYVpBBdDzXzMHKWZ9A4sn3cI/8DcjaMPmNUTt04slPpb8AYIGP00BVVDYU=
  file:
    - "hast-util-assert.js"
    - "hast-util-assert.min.js"
  on:
    tags: true
